apiVersion: apps/v1
kind: Deployment
metadata:
  name: task4-deployment
  labels:
    app: task4-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task4-app
  template:
    metadata:
      labels:
        app: task4-app
    spec:
      containers:
        - name: task4
          image: developmarat/task4:v2
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: task4-config
                  key: DATABASE_HOST
            - name: DATABASE_DB
              valueFrom:
                configMapKeyRef:
                  name: task4-config
                  key: DATABASE_DB
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: task4-config
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task4-secret
                  key: DATABASE_PASSWORD
          ports:
            - name: web
              containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 135
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 20